# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCT1105():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cT1105(self):
    self.driver.get("https://nexus-teste.streamlit.app/")
    self.driver.set_window_size(974, 1050)
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.CSS_SELECTOR, ".stColumn:nth-child(3) p").click()
    self.driver.find_element(By.ID, "text_input_1").click()
    self.driver.find_element(By.ID, "text_input_1").send_keys("Irinos")
    self.driver.find_element(By.ID, "text_input_2").send_keys("777")
    self.driver.find_element(By.CSS_SELECTOR, ".st-key-btn_entrar_login .st-emotion-cache-13lcgu3").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".st-key-btn_esqueci_login .st-emotion-cache-13lcgu3")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".st-ck:nth-child(3) p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".stColumn:nth-child(4) p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".st-ck:nth-child(2) p").click()
  
